export const movies = [
    {
        movie_aid: 1,
        movie_title: "Captain America: The Winter Soldier",
        movie_year: "2022",
        movie_duration: "2hr 12mins",
        movie_genre: "Thriller",
        movie_category: "International",
        movie_summary: "As Steve Rogers struggles to embrace his role in the modern world, he teams up with a fellow Avenger and S.H.I.E.L.D agent, Black Widow, to battle a new threat from history: an assassin known as the Winter Soldier.",
        movie_cast: "Chris Evans, Samuel L. Jackson, Scarlett Johansson",
        movie_image: "winter-soldier.jpg",
        movie_rating: "PG-13",
        movie_is_active: true,
    },
    {
        movie_aid: 2,
        movie_title: "Thor: Ragnarok",
        movie_year: "2022",
        movie_duration: "2hr 11mins",
        movie_genre: "Thriller",
        movie_category: "International",
        movie_summary: "Imprisoned on the planet Sakaar, Thor must race against time to return to Asgard and stop Ragnarök, the destruction of his world, at the hands of the powerful and ruthless villain Hela.",
        movie_cast: "Chris Hemsworth, Tom Hiddleston, Cate Blanchett",
        movie_image:"thor-ragnarok.png",
        movie_rating: "R 16+",
        movie_is_active: true,
    },
    {
        movie_aid: 3,
        movie_title: "Spider-Man: Far from Home",
        movie_year: "2019",
        movie_duration: "2hr 19mins",
        movie_genre: "Thriller",
        movie_category: "International",
        movie_summary: "Peter Parker, the beloved superhero Spider-Man, faces four destructive elemental monsters while on holiday in Europe. Soon, he receives help from Mysterio, a fellow hero with mysterious origins.",
        movie_cast: "Tom Holland, Samuel L. Jackson, Jake Gyllenhaal",
        movie_image: "spider-man.jpg",
        movie_rating: "R 16+",
        movie_is_active: true,
    },
    {
        movie_aid: 4,
        movie_title: "Ant-Man and the Wasp",
        movie_year: "2019",
        movie_duration: "2hr 2mins",
        movie_genre: "Thriller",
        movie_category: "International",
        movie_summary: "As Scott Lang balances being both a superhero and a father, Hope van Dyne and Dr. Hank Pym present an urgent new mission that finds the Ant-Man fighting alongside The Wasp to uncover secrets from their past.",
        movie_cast: "Paul Rudd, Evangeline Lilly, Michael Peña",
        movie_image: "ant-man.jpg",
        movie_rating: "PG-13",
        movie_is_active: true,
    },
    {
        movie_aid: 5,
        movie_title: "Black Widow",
        movie_year: "2021",
        movie_duration: "2hr 22mins",
        movie_genre: "Thriller",
        movie_category: "International",
        movie_summary: "Natasha Romanoff confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises.",
        movie_cast: "Scarlett Johansson, Florence Pugh, David Harbour",
        movie_image: "black-widow.jpg",
        movie_rating: "PG-13",
        movie_is_active: true,
    },
    {
        movie_aid: 6,
        movie_title: "Deadpool & Wolverine",
        movie_year: "2024",
        movie_duration: "3hr 12mins",
        movie_genre: "Thriller",
        movie_category: "International",
        movie_summary: "Deadpool is offered a place in the Marvel Cinematic Universe by the Time Variance Authority, but instead recruits a variant of Wolverine to save his universe from extinction.",
        movie_cast: "Ryan Reynolds, Hugh Jackman, Emma Corrin",
        movie_image: "deadpool-w.jpg",
        movie_rating: "PG-13",
        movie_is_active: true,
    },
    {
        movie_aid: 7,
        movie_title: "Deadpool & Wolverine",
        movie_year: "2024",
        movie_duration: "3hr 12mins",
        movie_genre: "Thriller",
        movie_category: "International",
        movie_summary: "Deadpool is offered a place in the Marvel Cinematic Universe by the Time Variance Authority, but instead recruits a variant of Wolverine to save his universe from extinction.",
        movie_cast: "Ryan Reynolds, Hugh Jackman, Emma Corrin",
        movie_image: "avengers.jpg",
        movie_rating: "PG-13",
        movie_is_active: true,
    },
    {
        movie_aid: 8,
        movie_title: "Deadpool & Wolverine",
        movie_year: "2024",
        movie_duration: "3hr 12mins",
        movie_genre: "Thriller",
        movie_category: "International",
        movie_summary: "Deadpool is offered a place in the Marvel Cinematic Universe by the Time Variance Authority, but instead recruits a variant of Wolverine to save his universe from extinction.",
        movie_cast: "Ryan Reynolds, Hugh Jackman, Emma Corrin",
        movie_image: "avengers.jpg",
        movie_rating: "PG-13",
        movie_is_active: true,
    },
    {
        movie_aid: 9,
        movie_title: "Deadpool & Wolverine",
        movie_year: "2024",
        movie_duration: "3hr 12mins",
        movie_genre: "Thriller",
        movie_category: "International",
        movie_summary: "Deadpool is offered a place in the Marvel Cinematic Universe by the Time Variance Authority, but instead recruits a variant of Wolverine to save his universe from extinction.",
        movie_cast: "Ryan Reynolds, Hugh Jackman, Emma Corrin",
        movie_image: "avengerse.jpg",
        movie_rating: "PG-13",
        movie_is_active: true,
    },
    {
        movie_aid: 10,
        movie_title: "Deadpool & Wolverine",
        movie_year: "2024",
        movie_duration: "3hr 12mins",
        movie_genre: "Thriller",
        movie_category: "Anime",
        movie_summary: "Deadpool is offered a place in the Marvel Cinematic Universe by the Time Variance Authority, but instead recruits a variant of Wolverine to save his universe from extinction.",
        movie_cast: "Ryan Reynolds, Hugh Jackman, Emma Corrin",
        movie_image: "aot.jpg",
        movie_rating: "PG-13",
        movie_is_active: true,
    },
    {
        movie_aid: 11,
        movie_title: "Deadpool & Wolverine",
        movie_year: "2024",
        movie_duration: "3hr 12mins",
        movie_genre: "Thriller",
        movie_category: "Anime",
        movie_summary: "Deadpool is offered a place in the Marvel Cinematic Universe by the Time Variance Authority, but instead recruits a variant of Wolverine to save his universe from extinction.",
        movie_cast: "Ryan Reynolds, Hugh Jackman, Emma Corrin",
        movie_image: "deathnote.jpg",
        movie_rating: "PG-13",
        movie_is_active: true,
    },
    {
        movie_aid: 12,
        movie_title: "Deadpool & Wolverine",
        movie_year: "2024",
        movie_duration: "3hr 12mins",
        movie_genre: "Thriller",
        movie_category: "Anime",
        movie_summary: "Deadpool is offered a place in the Marvel Cinematic Universe by the Time Variance Authority, but instead recruits a variant of Wolverine to save his universe from extinction.",
        movie_cast: "Ryan Reynolds, Hugh Jackman, Emma Corrin",
        movie_image: "dragonball.jpg",
        movie_rating: "PG-13",
        movie_is_active: true,
    },
    {
        movie_aid: 13,
        movie_title: "Deadpool & Wolverine",
        movie_year: "2024",
        movie_duration: "3hr 12mins",
        movie_genre: "Thriller",
        movie_category: "Anime",
        movie_summary: "Deadpool is offered a place in the Marvel Cinematic Universe by the Time Variance Authority, but instead recruits a variant of Wolverine to save his universe from extinction.",
        movie_cast: "Ryan Reynolds, Hugh Jackman, Emma Corrin",
        movie_image: "hero.jpg",
        movie_rating: "PG-13",
        movie_is_active: true,
    },
    {
        movie_aid: 14,
        movie_title: "Deadpool & Wolverine",
        movie_year: "2024",
        movie_duration: "3hr 12mins",
        movie_genre: "Thriller",
        movie_category: "Anime",
        movie_summary: "Deadpool is offered a place in the Marvel Cinematic Universe by the Time Variance Authority, but instead recruits a variant of Wolverine to save his universe from extinction.",
        movie_cast: "Ryan Reynolds, Hugh Jackman, Emma Corrin",
        movie_image: "hxh.jpg",
        movie_rating: "PG-13",
        movie_is_active: true,
    },
    {
        movie_aid: 15,
        movie_title: "Deadpool & Wolverine",
        movie_year: "2024",
        movie_duration: "3hr 12mins",
        movie_genre: "Thriller",
        movie_category: "Anime",
        movie_summary: "Deadpool is offered a place in the Marvel Cinematic Universe by the Time Variance Authority, but instead recruits a variant of Wolverine to save his universe from extinction.",
        movie_cast: "Ryan Reynolds, Hugh Jackman, Emma Corrin",
        movie_image: "jujutsu.jpg",
        movie_rating: "PG-13",
        movie_is_active: true,
    },
    {
        movie_aid: 16,
        movie_title: "Deadpool & Wolverine",
        movie_year: "2024",
        movie_duration: "3hr 12mins",
        movie_genre: "Thriller",
        movie_category: "Anime",
        movie_summary: "Deadpool is offered a place in the Marvel Cinematic Universe by the Time Variance Authority, but instead recruits a variant of Wolverine to save his universe from extinction.",
        movie_cast: "Ryan Reynolds, Hugh Jackman, Emma Corrin",
        movie_image: "kimetsu.jpg",
        movie_rating: "PG-13",
        movie_is_active: true,
    },
    {
        movie_aid: 17,
        movie_title: "Deadpool & Wolverine",
        movie_year: "2024",
        movie_duration: "3hr 12mins",
        movie_genre: "Thriller",
        movie_category: "Anime",
        movie_summary: "Deadpool is offered a place in the Marvel Cinematic Universe by the Time Variance Authority, but instead recruits a variant of Wolverine to save his universe from extinction.",
        movie_cast: "Ryan Reynolds, Hugh Jackman, Emma Corrin",
        movie_image: "one-piece.jpg",
        movie_rating: "PG-13",
        movie_is_active: true,
    },
    {
        movie_aid: 18,
        movie_title: "Deadpool & Wolverine",
        movie_year: "2024",
        movie_duration: "3hr 12mins",
        movie_genre: "Thriller",
        movie_category: "Kdrama",
        movie_summary: "Deadpool is offered a place in the Marvel Cinematic Universe by the Time Variance Authority, but instead recruits a variant of Wolverine to save his universe from extinction.",
        movie_cast: "Ryan Reynolds, Hugh Jackman, Emma Corrin",
        movie_image: "k-drama-1.png",
        movie_rating: "PG-13",
        movie_is_active: true,
    },
    {
        movie_aid: 19,
        movie_title: "Deadpool & Wolverine",
        movie_year: "2024",
        movie_duration: "3hr 12mins",
        movie_genre: "Thriller",
        movie_category: "Kdrama",
        movie_summary: "Deadpool is offered a place in the Marvel Cinematic Universe by the Time Variance Authority, but instead recruits a variant of Wolverine to save his universe from extinction.",
        movie_cast: "Ryan Reynolds, Hugh Jackman, Emma Corrin",
        movie_image: "k-drama-2.png",
        movie_rating: "PG-13",
        movie_is_active: true,
    },
    {
        movie_aid: 20,
        movie_title: "Deadpool & Wolverine",
        movie_year: "2024",
        movie_duration: "3hr 12mins",
        movie_genre: "Thriller",
        movie_category: "Kdrama",
        movie_summary: "Deadpool is offered a place in the Marvel Cinematic Universe by the Time Variance Authority, but instead recruits a variant of Wolverine to save his universe from extinction.",
        movie_cast: "Ryan Reynolds, Hugh Jackman, Emma Corrin",
        movie_image: "k-drama-3.png",
        movie_rating: "PG-13",
        movie_is_active: true,
    },
    {
        movie_aid: 21,
        movie_title: "Deadpool & Wolverine",
        movie_year: "2024",
        movie_duration: "3hr 12mins",
        movie_genre: "Thriller",
        movie_category: "Kdrama",
        movie_summary: "Deadpool is offered a place in the Marvel Cinematic Universe by the Time Variance Authority, but instead recruits a variant of Wolverine to save his universe from extinction.",
        movie_cast: "Ryan Reynolds, Hugh Jackman, Emma Corrin",
        movie_image: "k-drama-4.png",
        movie_rating: "PG-13",
        movie_is_active: true,
    },
    {
        movie_aid: 24,
        movie_title: "Deadpool & Wolverine",
        movie_year: "2024",
        movie_duration: "3hr 12mins",
        movie_genre: "Thriller",
        movie_category: "Kdrama",
        movie_summary: "Deadpool is offered a place in the Marvel Cinematic Universe by the Time Variance Authority, but instead recruits a variant of Wolverine to save his universe from extinction.",
        movie_cast: "Ryan Reynolds, Hugh Jackman, Emma Corrin",
        movie_image: "k-drama-5.png",
        movie_rating: "PG-13",
        movie_is_active: true,
    },
    {
        movie_aid: 25,
        movie_title: "Deadpool & Wolverine",
        movie_year: "2024",
        movie_duration: "3hr 12mins",
        movie_genre: "Thriller",
        movie_category: "Kdrama",
        movie_summary: "Deadpool is offered a place in the Marvel Cinematic Universe by the Time Variance Authority, but instead recruits a variant of Wolverine to save his universe from extinction.",
        movie_cast: "Ryan Reynolds, Hugh Jackman, Emma Corrin",
        movie_image: "k-drama-6.png",
        movie_rating: "PG-13",
        movie_is_active: true,
    },
    {
        movie_aid: 26,
        movie_title: "Deadpool & Wolverine",
        movie_year: "2024",
        movie_duration: "3hr 12mins",
        movie_genre: "Thriller",
        movie_category: "Kdrama",
        movie_summary: "Deadpool is offered a place in the Marvel Cinematic Universe by the Time Variance Authority, but instead recruits a variant of Wolverine to save his universe from extinction.",
        movie_cast: "Ryan Reynolds, Hugh Jackman, Emma Corrin",
        movie_image: "k-drama-7.png",
        movie_rating: "PG-13",
        movie_is_active: true,
    },
    {
        movie_aid: 27,
        movie_title: "Deadpool & Wolverine",
        movie_year: "2024",
        movie_duration: "3hr 12mins",
        movie_genre: "Thriller",
        movie_category: "Kdrama",
        movie_summary: "Deadpool is offered a place in the Marvel Cinematic Universe by the Time Variance Authority, but instead recruits a variant of Wolverine to save his universe from extinction.",
        movie_cast: "Ryan Reynolds, Hugh Jackman, Emma Corrin",
        movie_image: "k-drama-8.png",
        movie_rating: "PG-13",
        movie_is_active: true,
    },

   
]