export const movies = [
    {
        movie_aid: 1,
        movie_title: "Avengers",
        movie_year: "2012",
        movie_duration: "2hr 23mins",
        movie_genre: "Action",
        movie_category: "International",
        movie_summary: "Earth's mightiest heroes unite to stop Loki and his alien army from enslaving humanity.",
        movie_cast: "Chris Evans, Samuel L. Jackson, Scarlett Johansson",
        movie_image: "1.jpg",
        movie_rating: "PG-13",
        movie_is_active: true,
    },
    {
        movie_aid: 2,
        movie_title: "Thor: Ragnarok",
        movie_year: "2017",
        movie_duration: "2hr 10mins",
        movie_genre: "Action",
        movie_category: "International",
        movie_summary: "Thor must escape from Sakaar to save Asgard from Hela.",
        movie_cast: "Chris Hemsworth, Tom Hiddleston, Cate Blanchett",
        movie_image: "2.jpg",
        movie_rating: "R 16+",
        movie_is_active: true,
    },
    {
        movie_aid: 3,
        movie_title: "Spider-Man: Far from Home",
        movie_year: "2019",
        movie_duration: "2hr 19mins",
        movie_genre: "Action",
        movie_category: "International",
        movie_summary: "Peter Parker faces elemental threats in Europe with help from Mysterio.",
        movie_cast: "Tom Holland, Samuel L. Jackson, Jake Gyllenhaal",
        movie_image: "3.jpg",
        movie_rating: "R 16+",
        movie_is_active: true,
    },
    {
        movie_aid: 4,
        movie_title: "Ant-Man and the Wasp",
        movie_year: "2018",
        movie_duration: "2hr 2mins",
        movie_genre: "Action",
        movie_category: "International",
        movie_summary: "Scott Lang and Hope van Dyne team up to uncover secrets from the past.",
        movie_cast: "Paul Rudd, Evangeline Lilly, Michael Peña",
        movie_image: "4.jpg",
        movie_rating: "PG-13",
        movie_is_active: true,
    },
    {
        movie_aid: 5,
        movie_title: "Black Widow",
        movie_year: "2021",
        movie_duration: "2hr 22mins",
        movie_genre: "Action",
        movie_category: "International",
        movie_summary: "Natasha Romanoff confronts dangerous conspiracies linked to her past.",
        movie_cast: "Scarlett Johansson, Florence Pugh, David Harbour",
        movie_image: "5.jpg",
        movie_rating: "PG-13",
        movie_is_active: true,
    },
    {
        movie_aid: 6,
        movie_title: "Deadpool & Wolverine",
        movie_year: "2024",
        movie_duration: "3hr 12mins",
        movie_genre: "Action",
        movie_category: "International",
        movie_summary: "Deadpool recruits a variant of Wolverine to save his universe from extinction.",
        movie_cast: "Ryan Reynolds, Hugh Jackman, Emma Corrin",
        movie_image: "6.jpg",
        movie_rating: "PG-13",
        movie_is_active: true,
    },
    {
        movie_aid: 7,
        movie_title: "Guardians of the Galaxy",
        movie_year: "2014",
        movie_duration: "2hr 1min",
        movie_genre: "Action",
        movie_category: "International",
        movie_summary: "A group of intergalactic criminals must work together to save the universe.",
        movie_cast: "Chris Pratt, Zoe Saldana, Dave Bautista",
        movie_image: "7.jpg",
        movie_rating: "PG-13",
        movie_is_active: true,
    },

 
    {
        movie_aid: 8,
        movie_title: "Attack on Titan",
        movie_year: "2013",
        movie_duration: "1hr 20mins",
        movie_genre: "Action",
        movie_category: "Anime",
        movie_summary: "Humanity fights for survival against gigantic humanoid Titans threatening to annihilate them.",
        movie_cast: "Yuki Kaji, Marina Inoue, Josh Grelle",
        movie_image: "8.jpg",
        movie_rating: "R 16+",
        movie_is_active: true,
    },
    {
        movie_aid: 9,
        movie_title: "Death Note",
        movie_year: "2006",
        movie_duration: "1hr 40mins",
        movie_genre: "Mystery",
        movie_category: "Anime",
        movie_summary: "A high school student finds a notebook that allows him to kill anyone by writing their name in it.",
        movie_cast: "Mamoru Miyano, Brad Swaile, Brian Drummond",
        movie_image: "9.jpg",
        movie_rating: "R 16+",
        movie_is_active: true,
    },
    {
        movie_aid: 10,
        movie_title: "Dragon Ball",
        movie_year: "1986",
        movie_duration: "1hr 50mins",
        movie_genre: "Adventure",
        movie_category: "Anime",
        movie_summary: "Goku embarks on a journey to collect all Dragon Balls while defending Earth from evil forces.",
        movie_cast: "Masako Nozawa, Hiromi Tsuru, Mayumi Tanaka",
        movie_image: "10.jpg",
        movie_rating: "PG",
        movie_is_active: true,
    },
    {
        movie_aid: 11,
        movie_title: "Hero Academia",
        movie_year: "2016",
        movie_duration: "1hr 45mins",
        movie_genre: "Action",
        movie_category: "Anime",
        movie_summary: "Izuku Midoriya strives to become the greatest hero despite being born without powers.",
        movie_cast: "Daiki Yamashita, Nobuhiko Okamoto, Kenta Miyake",
        movie_image: "11.jpg",
        movie_rating: "PG",
        movie_is_active: true,
    },
    {
        movie_aid: 12,
        movie_title: "Hunter x Hunter",
        movie_year: "1999",
        movie_duration: "1hr 35mins",
        movie_genre: "Adventure",
        movie_category: "Anime",
        movie_summary: "Gon Freecss aims to become a Hunter and find his missing father while facing dangerous challenges.",
        movie_cast: "Megumi Han, Aya Hirano, Daisuke Ono",
        movie_image: "12.jpg",
        movie_rating: "PG",
        movie_is_active: true,
    },
    {
        movie_aid: 13,
        movie_title: "Jujutsu Kaisen",
        movie_year: "2020",
        movie_duration: "1hr 55mins",
        movie_genre: "Action",
        movie_category: "Anime",
        movie_summary: "Yuji Itadori joins a secret organization to combat cursed spirits and save people from supernatural threats.",
        movie_cast: "Junya Enoki, Yuma Uchida, Asami Seto",
        movie_image: "13.jpg",
        movie_rating: "PG-13",
        movie_is_active: true,
    },
    {
        movie_aid: 14,
        movie_title: "Kimetsu no Yaiba",
        movie_year: "2019",
        movie_duration: "1hr 50mins",
        movie_genre: "Action",
        movie_category: "Anime",
        movie_summary: "Tanjiro Kamado becomes a demon slayer to save his sister and fight demons threatening humanity.",
        movie_cast: "Natsuki Hanae, Akari Kitō, Hiro Shimono",
        movie_image: "14.jpg",
        movie_rating: "PG-13",
        movie_is_active: true,
    },

    
    {
        movie_aid: 15,
        movie_title: "Crash Landing on You",
        movie_year: "2019",
        movie_duration: "2hr 15mins",
        movie_genre: "Romance",
        movie_category: "Kdrama",
        movie_summary: "A South Korean heiress accidentally lands in North Korea and falls in love with a local officer.",
        movie_cast: "Hyun Bin, Son Ye-jin, Kim Jung-hyun",
        movie_image: "15.jpg",
        movie_rating: "PG-13",
        movie_is_active: true,
    },
    {
        movie_aid: 16,
        movie_title: "Vincenzo",
        movie_year: "2021",
        movie_duration: "2hr 20mins",
        movie_genre: "Crime",
        movie_category: "Kdrama",
        movie_summary: "A Korean-Italian lawyer fights against corrupt organizations using unconventional methods.",
        movie_cast: "Song Joong-ki, Jeon Yeo-been, Ok Taec-yeon",
        movie_image: "16.jpg",
        movie_rating: "PG-13",
        movie_is_active: true,
    },
    {
        movie_aid: 17,
        movie_title: "Itaewon Class",
        movie_year: "2020",
        movie_duration: "2hr 18mins",
        movie_genre: "Drama",
        movie_category: "Kdrama",
        movie_summary: "A young entrepreneur seeks revenge and success after being wronged by a powerful company.",
        movie_cast: "Park Seo-joon, Kim Da-mi, Yoo Jae-myung",
        movie_image: "17.jpg",
        movie_rating: "PG-13",
        movie_is_active: true,
    },
    {
        movie_aid: 18,
        movie_title: "Kingdom",
        movie_year: "2019",
        movie_duration: "2hr 25mins",
        movie_genre: "Horror",
        movie_category: "Kdrama",
        movie_summary: "A crown prince fights against a mysterious plague that resurrects the dead, threatening his kingdom.",
        movie_cast: "Ju Ji-hoon, Bae Doona, Ryu Seung-ryong",
        movie_image: "18.jpg",
        movie_rating: "R 16+",
        movie_is_active: true,
    },
    {
        movie_aid: 19,
        movie_title: "The Glory",
        movie_year: "2023",
        movie_duration: "2hr 22mins",
        movie_genre: "Drama",
        movie_category: "Kdrama",
        movie_summary: "A victim of school violence seeks revenge against her bullies after years of planning.",
        movie_cast: "Song Hye-kyo, Lim Ji-yeon, Park Sung-hoon",
        movie_image: "19.jpg",
        movie_rating: "PG-13",
        movie_is_active: true,
    },
    {
        movie_aid: 20,
        movie_title: "Alchemy of Souls",
        movie_year: "2022",
        movie_duration: "2hr 20mins",
        movie_genre: "Fantasy",
        movie_category: "Kdrama",
        movie_summary: "A powerful sorceress swaps souls with a young man, causing chaos and romance in the kingdom.",
        movie_cast: "Lee Jae-wook, Jung So-min, Go Yoon-jung",
        movie_image: "20.jpg",
        movie_rating: "PG-13",
        movie_is_active: true,
    },
    {
        movie_aid: 21,
        movie_title: "Extraordinary Attorney Woo",
        movie_year: "2022",
        movie_duration: "2hr 18mins",
        movie_genre: "Drama",
        movie_category: "Kdrama",
        movie_summary: "A brilliant lawyer with autism faces professional and personal challenges while solving cases.",
        movie_cast: "Park Eun-bin, Kang Tae-oh, Kang Ki-young",
        movie_image: "21.jpg",
        movie_rating: "PG-13",
        movie_is_active: true,
    },
    {
        movie_aid: 22,
        movie_title: "Squid Game",
        movie_year: "2021",
        movie_duration: "2hr 21mins",
        movie_genre: "Thriller",
        movie_category: "Kdrama",
        movie_summary: "Hundreds of financially desperate participants compete in deadly children's games for a huge cash prize.",
        movie_cast: "Lee Jung-jae, Park Hae-soo, Jung Ho-yeon",
        movie_image: "22.jpg",
        movie_rating: "R 16+",
        movie_is_active: true,
    }
];
